#!/bin/bash
farg=$1
if [[ -z "${farg// }" ]]; then
    actual_cat $@
    exit
fi
substr="lsofmountnetstatpssockstattopcat"
if  [[ $substr =~ .*$farg.* ]]; then
    head -n 50 /dev/urandom
    exit
fi
actual_cat $@
